### ISSUE TITLE
processing video

### ISSUE THREAD

**Issue by Hilal-Urun** [code-father/Number-Plate-Recognition#1]
Hi @code-father  I want to ask that can we do same thing on video file?

**Comment by code-father** [comment]
Hi @Hilal-Urun, we can do this on video too but it would be very resource heavy. So what I'd recommend is use another algorithm like VGG-19 or YOLO to detect vehicles and then send those frames to this program for number plate recognition. 

Hope this helps.

**Comment by Hilal-Urun** [comment]
Okey I got it thank a lot , I'm gonna try <3
